### ISSUE TITLE
Support for RTL languages

### ISSUE THREAD

**Issue by barantes** [jesualex/sTooltip#2]
Hi, thanks for writing this lib. I was planning to use in my app because it's really straightforward to use, but I just found that the tooltips won't work well when the phone is set to Hebrew (and probably to other RTL languages). I hope you can fix it soon. 

Cheers.

Bruno.

**Comment by jesualex** [comment]
Hi @barantes 

Can you send me any detail of the error?

**Comment by barantes** [comment]
Sorry, I've switched to another lib so I don't have any sample code anymore. Anyway, there was no exception being thrown. The issue was that the tooltip bubble was positioned outside the screen when I switched the device language to Hebrew. Perhaps you may replicate the issue simply by switching your phone's language to Hebrew or some other RTL language.

**Comment by jesualex** [comment]
don't worry, thanks also for your contribution, i'll see it
