### ISSUE TITLE
Tooltip is not close on list scroll

### ISSUE THREAD

**Issue by dharmesh395** [jesualex/sTooltip#4]
I have open tooltip on click of list item in list Adapter but now problem is that, on scrolling it is not hiding.
Please help to resolved this issue.

**Comment by jesualex** [comment]
Hi @dharmesh395 can you send me a little project or code to replicate the issue?

**Comment by dharmesh395** [comment]
Project is not available on Play Store. Another issue is that, if tooltip is open and we move to other screen then also it is not hide.

**Comment by jesualex** [comment]
the tooltip will not hide because the view to which it was attached is still alive, so that would not be an issue, the issue of the scroll maybe yes, but i need at least a piece of code to be able to replicate and find a solution

**Comment by jesualex** [comment]
no response.
